---
docker_http_proxy: "{{ ansible_env.http_proxy | default(None) }}"
docker_https_proxy: "{{ ansible_env.https_proxy  | default(None)}}"
docker_no_proxy_params: "{{ ansible_env.no_proxy | default(None) }}"
docker_compose_install_method: pip
proxy_env:
  http_proxy: "{{ ansible_env.http_proxy | default(None) }}"
  https_proxy: "{{ ansible_env.https_proxy  | default(None)}}"
  no_proxy: "{{ ansible_env.no_proxy | default(None) }}"
# Custo
#docker_apt_key_url: http://nexus/nexus/repository/docker-project/linux/{{ansible_os_family|lower}}/gpg
#docker_apt_repo_url: "deb [arch=amd64] http://nexus/nexus/repository/docker-project/linux/{{ansible_os_family|lower}} {{ ansible_distribution_release }} stable"
#docker_compose_pip_extra_args: -i http://nexus/nexus/repository/pypi/simple --trusted-host nexus
#docker_compose_curl_url: 'http://nexus/nexus/repository/docker-compose/download/{{ docker_compose_version }}/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}'
#
#ntp_config_server:
#  - "192.168.1.1"
#  - "192.168.1.2"
docker_config:
  mtu: 1450
  data-root: /DATA/docker
#docker_dns:
#  - "192.168.1.1"
#  - "192.168.1.2"
#docker_dns_search:
#  - mydomain.com
#docker_insecure_registries:
#  - nexus
#  - localhost.local
#docker_registry_mirrors:
#  - http://nexus
docker_users:
  - deploy-user
