heat_template_version: 2015-10-15

description: >
  Data volume

parameters:
  data_size:
    type: number
    description: The size of the Cinder data volume for instance
    default: 10
  vol_type:
    type: string
    description: The volume type of the Cinder volume
    default: default

resources:
  data_volume:
    type: OS::Cinder::Volume
    properties:
      size: { get_param: data_size }
      volume_type: { get_param: vol_type }

outputs:
  data_volume_id:
    value: { get_resource: data_volume }

