heat_template_version: 2015-10-15

description: Template that installs a HAProxy server.

parameters:
  stack:
    type: string
    default: ""
  context:
    type: string
    default: ""
  image:
    type: string
    label: Image name or ID
    description: Image to be used for server. Please use an Ubuntu based image.
    default: trusty-server-cloudimg-amd64
  flavor:
    type: string
    label: Flavor
    description: Type of instance (flavor) to be used on the compute instance.
    default: m1.small
  vol_size:
    type: number
    description: The size of the Cinder root volume for instance
    default: 10
  vol_type:
    type: string
    description: The volume type of the Cinder volume for instance
    default: default
  key_name:
    type: string
    label: Key name
    description: Name of key-pair to be installed on the compute instance.
    default: my_key

  dns_nameservers:
    type: comma_delimited_list
    label: DNS nameservers
    description: dns_nameservers=8.8.8.8,8.8.4.4
  floatingip_network_name:
    type: string
  floatingip_id:
    type: string
  lb_subnet_cidr:
    type: string
    default: "192.168.1.0/24"
# LB configuration backend
  servers:
    type: comma_delimited_list
    label: Servers
    description: Comma separated list of servers in the cluster.
  port_number:
    type: number
    label: Port number
    description: Port number to proxy.
    default: 80
  color:
    type: string
    label: stack color (blue/gren)
    default: blue

resources:
  random:
    type: OS::Heat::RandomString
    properties:
      length: 6
      sequence: lettersdigits

  extrouter:
    type: OS::Neutron::Router
    properties:
      external_gateway_info:
        network: { get_param: floatingip_network_name }

  lb_network:
    depends_on: [ random ]
    type: OS::Neutron::Net
    properties:
      admin_state_up: True
      name:
        str_replace:
          template: stack%-ctx%-ress%-rand%
          params:
            "stack%": { get_param: 'stack' }
            "ctx%": {get_param: context}
            "ress%": "lb-net"
            "rand%": { get_attr: [random, value] }
      shared: False

  lb_subnet:
    type: OS::Neutron::Subnet
    depends_on: [ lb_network ]
    properties:
      name:
        str_replace:
          template: stack%-ctx%-ress%-rand%
          params:
            "stack%": { get_param: stack }
            "ctx%": { get_param: context}
            "ress%": "lb-subnet"
            "rand%": { get_attr: [random, value] }
      cidr: {get_param: lb_subnet_cidr}
      network_id: {get_resource: lb_network}
      dns_nameservers: {get_param: dns_nameservers}
      enable_dhcp: True
      ip_version: 4

  lb_interface:
    type: OS::Neutron::RouterInterface
    depends_on: [ lb_subnet, extrouter ]
    properties:
      router_id: { get_resource: extrouter }
      subnet_id: { get_resource: lb_subnet }

  wait_condition:
    type: OS::Heat::WaitCondition
    properties:
      handle: { get_resource: wait_handle }
      count: 1
      timeout: 600

  wait_handle:
    type: OS::Heat::WaitConditionHandle

  security_group:
      type: OS::Neutron::SecurityGroup
      properties:
        name: web_server_security_group
        rules:
          - protocol: tcp
            port_range_min: { get_param: port_number }
            port_range_max: { get_param: port_number }
  security_group_ssh:
      type: OS::Neutron::SecurityGroup
      properties:
        name: ssh_server_security_group
        rules:
          - remote_ip_prefix: 0.0.0.0/0
            protocol: tcp
            port_range_min: 22
            port_range_max: 22
            direction: ingress

  port:
    type: OS::Neutron::Port
    properties:
      name:
        str_replace:
          template: stack%-ctx%-ress%-%index%
          params:
            "stack%": { get_param: stack }
            "ctx%": {get_param: context}
            "ress%": "lb"
            "rand%": { get_attr: [random, value] }
      network: { get_resource: lb_network }
      security_groups:
        - { get_resource: security_group }
        - { get_resource: security_group_ssh }
      replacement_policy: AUTO

  floating:
    type: OS::Neutron::FloatingIPAssociation
    depends_on: [ port ]
    properties:
      floatingip_id: { get_param: floatingip_id }
      port_id: { get_resource: port }

  root_volume:
    type: OS::Cinder::Volume
    properties:
      image: { get_param: image }
      size: { get_param: vol_size }
      volume_type: { get_param: vol_type }

  haproxy_instance:
    type: OS::Nova::Server
    depends_on: [ extrouter, lb_network, lb_interface, lb_subnet, port, root_volume ]
    properties:
      name:
        str_replace:
          template: stack%-ctx%-ress%
          params:
            "stack%": { get_param: stack }
            "ctx%": {get_param: context}
            "ress%": "lb"
# Boot on ephemeral disk
#      image: { get_param: image }
# Boot on volume
      block_device_mapping_v2: [{ device_name: "vda", volume_id : { get_resource : root_volume }, delete_on_termination : true }]
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource: port }
      metadata:
        servers: { get_param: servers }
        color: { get_param: color }
      user_data_format: RAW
      user_data:
        str_replace:
          params:
            __port__: { get_param: port_number }
            wc_notify: { get_attr: ['wait_handle', 'curl_cli'] }
          template: |
            #!/bin/bash -ex
            function clean() {
             [ "$?" -gt 0 ] && wc_notify -k --data-binary '{"status": "FAILURE"}'
            }
            trap clean EXIT QUIT KILL

            # install dependencies
            apt-get update
            apt-get -y install build-essential python python-dev python-virtualenv supervisor haproxy curl

            sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

            # save haproxy original configuration
            cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy_base.cfg

            # write an initial empty list of worker servers
            cat >>/etc/haproxy/servers.json <<EOF
            []
            EOF

            # write the update script
            cat >>/etc/haproxy/update.py <<EOF
            import sys
            import json
            import subprocess

            # load server list from metadata
            metadata = json.loads(sys.stdin.read())
            new_servers = json.loads(metadata.get('meta', {}).get('servers', '[]'))
            if not new_servers:
                sys.exit(1)  # bad metadata

            # compare against known list of servers
            current_servers = json.loads(open('/etc/haproxy/servers.json').read())
            if current_servers == new_servers:
                sys.exit(0)  # no changes

            # record updated list of servers
            open('/etc/haproxy/servers.json', 'wt').write(json.dumps(new_servers))

            # generate a new haproxy config file
            f = open('/etc/haproxy/haproxy.cfg', 'wt')
            f.write(open('/etc/haproxy/haproxy_base.cfg').read())
            f.write("""
            frontend http
               bind *:80
               default_backend web-servers
            backend web-servers
                mode http
                balance roundrobin
                option httpclose
                option forwardfor
            """)
            for i, server in enumerate(new_servers):
                f.write('    server server-{0} {1}:{2}\n'.format(i, server, __port__))
            f.close()

            # reload haproxy's configuration
            print('Reloading haproxy with servers: ' + ', '.join(new_servers))
            subprocess.call(['service', 'haproxy', 'restart'])
            EOF

            # add a cron job to monitor the metadata and update haproxy
            crontab -l >_crontab || true
            echo "PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin" >_crontab
            echo "* * * * * curl -s http://169.254.169.254/openstack/latest/meta_data.json | python /etc/haproxy/update.py | /usr/bin/logger -t haproxy_update" >>_crontab
            crontab <_crontab
            rm _crontab
            service haproxy stop
            service haproxy start
            curl -s http://169.254.169.254/openstack/latest/meta_data.json | python /etc/haproxy/update.py | /usr/bin/logger -t haproxy_update

            update-rc.d postfix disable
            service postfix stop
            # let Heat know that we are done here
            wc_notify -k --data-binary '{"status": "SUCCESS"}'

outputs:
  name:
    description: Name of the HAProxy instance.
    value: { get_attr: [haproxy_instance, name] }
  ip:
    description: The IP address of the HAProxy instance.
    value: { get_attr: [haproxy_instance, first_address] }
  port:
    description: The network port of the HAProxy instance.
    value: { get_resource: port }
