#cloud-config
merge_how: dict(recurse_array)+list(append)
write_files:
  - path: /root/openrc
    owner: root:root
    permissions: '0600'
    content: |
      #!/bin/bash
      # generated openrc
      meta_data_json=$(http_proxy="" https_proxy="" /usr/bin/curl --fail -s http://169.254.169.254/openstack/latest/meta_data.json )
      export OS_TOKEN="$(echo $meta_data_json | jq -r .meta.os_token)"
      export OS_PROJECT_ID="$(echo $meta_data_json | jq -r .meta.os_project_id)"
      export OS_AUTH_URL="$os_auth_url"
