heat_template_version: 2015-10-15

description: >
  Build network, and deploy en instannce

parameters:
  key_name:
    type: string
    label: Name of keypair to assign to servers
    description: key_name=foo
  count:
    type: number
    label: number of instance
    default: 1

  subnet_cidr:
    type: string
    default: "192.168.1.0/24"
  subnet_start:
    type: string
    default: "192.168.1.100"
  subnet_end:
    type: string
    default: "192.168.1.200"
  gateway_ip:
    type: string
    default: "192.168.1.254"
  dns_nameservers:
    type: comma_delimited_list
    label: DNS nameservers
    description: dns_nameservers=8.8.8.8,8.8.4.4
  floatingip_network_name:
    type: string
    label: The Floating Network
    description: floatingip_network_name=public
  flavor:
    type: string
    label: The flavor for bastion Instances
    description: flavor=small
  image:
    type: string
    label: The debian image based for Instances
    description: image=debian-8-latest
    default: debian-8-latest
  vol_size:
    type: number
    description: The size of the Cinder root volume for instance
    default: 10
  vol_type:
    type: string
    description: The volume type of the Cinder volume for instance
    default: default

resources:
  extrouter:
    type: OS::Neutron::Router
    properties:
      external_gateway_info:
        network: { get_param: floatingip_network_name }

  network:
    type: OS::Neutron::Net

  subnet:
    type: OS::Neutron::Subnet
    properties:
      cidr: {get_param: subnet_cidr}
      network: {get_resource: network}
      allocation_pools: [{"start" : {get_param: subnet_start}, "end" : {get_param: subnet_end}}]
      dns_nameservers: {get_param: dns_nameservers}
      enable_dhcp: True
      gateway_ip: {get_param: gateway_ip}
      ip_version: 4

  interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: extrouter }
      subnet_id: { get_resource: subnet }

  security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      rules:
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 22
          port_range_max: 22
          direction: ingress
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 80
          port_range_max: 80
          direction: ingress
        - remote_ip_prefix: 0.0.0.0/0
          protocol: icmp
          direction: ingress

  instance:
    type: OS::Heat::ResourceGroup
    properties:
      count: { get_param: count }
      resource_def:
        type: server.yaml
        properties:
          key_name: { get_param: key_name }
          image: { get_param : image }
          flavor: { get_param: flavor }
          vol_size: { get_param: vol_size }
          vol_type: { get_param: vol_type }
          network: { get_resource: network }
          security_groups: [ { get_resource: security_group } ]
          floatingip_network_name: { get_param: floatingip_network_name }

outputs:
