#!/bin/bash
#
# REPOSITORY_URL
# REPOSITORY_USERNAME
# REPOSITORY_PASSWORD
set -e

REPOSITORY_URL=${REPOSITORY_URL:-http://nexus/nexus/repository/heat-build/}
REPOSITORY_USERNAME=${REPOSITORY_USERNAME:? REPOSITORY_USERNAME not defined }
REPOSITORY_PASSWORD=${REPOSITORY_PASSWORD:? REPOSITORY_PASSWORD not defined}

PACKAGENAME=${1:? $(basename $0) PACKAGENAME VERSION needed}
VERSION=${2:? $(basename $0) PACKAGENAME VERSION needed}
LONG_PACKAGENAME=${PACKAGENAME}-${VERSION}
FILENAME=${LONG_PACKAGENAME}.tar.gz
PACKAGEDIR=dist

[ -f $PACKAGEDIR/$FILENAME ] || exit 1

curl -LS -u $REPOSITORY_USERNAME:$REPOSITORY_PASSWORD --upload-file $PACKAGEDIR/$FILENAME  $REPOSITORY_URL/${PACKAGENAME}/${VERSION}/$FILENAME
echo "Published ($?): $REPOSITORY_URL/${PACKAGENAME}/${VERSION}/$FILENAME"
